[package]
name = "lwip_rust"
version = "0.1.0"
edition = "2021"
authors = ["Haixuan Tong <haix.tong@gmail.com>"]
description = "Rust wrapper of lwip net stack"
license = "GPL-3.0-or-later OR Apache-2.0"
homepage = "https://github.com/rcore-os/arceos"
repository = "https://github.com/rcore-os/arceos/tree/main/crates/lwip_rust"
documentation = "https://rcore-os.github.io/arceos/lwip_rust/index.html"

[build-dependencies]
bindgen = "0.65.1"
cc = { version = "1.0.79", features = ["parallel"] }
