[package]
name = "jbd"
version = "0.1.0"
edition = "2021"
authors = ["Liang Yesheng <liang2kl@outlook.com>"]
description = "The journaling block device layer for file systems"

[features]
log_off = ["log/max_level_off"]
log_error = ["log/max_level_error"]
log_warn = ["log/max_level_warn"]
log_info = ["log/max_level_info"]
log_debug = ["log/max_level_debug", "log/release_max_level_debug"]
log_trace = ["log/max_level_trace"]
debug = ["log_debug"]
default = ["log_error"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0"
bitflags = "1.2.1"
# spin = "0.7.0"
log = "0.4"

[dev-dependencies]
rand = "0.8"
env_logger = "0.10.0"