[package]
name = "easy_fs"
version = "0.1.0"
authors = ["Yifan Wu <shinbokuow@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
journal = ["dep:jbd"]

[dependencies]
spin = "0.7.0"
cfg-if = "1.0"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
axfs_vfs = { path = "../../../../crates/axfs_vfs" }
axfs = { path = "../../../../modules/axfs", features = ["myfs"] }
crate_interface = { path = "../../../../crates/crate_interface" }
jbd = { path = "../../../../crates/jbd", optional = true, features = ["log_debug", "debug"] }
axlog = { path = "../../../../modules/axlog", features = ["log-level-trace"] }